Repository ComputationalRadiationPhysics/redGrapes, pull requests merged in 2023-12, with the labels that each got.

#47 fix broken example
  examples/1_resources.cpp
Labels: bug

#48 ChunkedList: store pointers to next/last elements instead of indices …
  redGrapes/resource/resource.cpp
  redGrapes/resource/resource.hpp
  redGrapes/resource/resource_user.cpp
  redGrapes/resource/resource_user.hpp
  redGrapes/scheduler/event.cpp
  redGrapes/scheduler/event.hpp
  redGrapes/util/atomic_list.hpp
  redGrapes/util/chunked_list.hpp
Labels: optimization

#50 only allocate memory if needed
  redGrapes/util/atomic_list.hpp
  redGrapes/util/chunked_list.hpp
Labels: refactoring

#51 fix AtomicList & improve ChunkedList
  redGrapes/util/atomic_list.hpp
  redGrapes/util/chunked_list.hpp
Labels: bug

#53 Fix freeze of worker
  redGrapes/dispatch/thread/worker.cpp
  redGrapes/dispatch/thread/worker.hpp
Labels: bug
